# Gathering user data
name=input("Enter a name:")
action=input("Enter an action(verb ending in -ing):")
place=input("Enter a place:")
feeling=input("How are you feeling today?")
Food=input("Enter a food:")
Friend=input("Enter the name of your friend:")
Teacher=input("Enter a teacher:")
Adjective=input(" Enter an adjective:")
Time=input("Enter a time:")